name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    env: 
     # GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildon: [pull_request]
      on: [pull_request]
  jobs:
    scan:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Run AppScan CodeSweep
          uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
          with:
            asoc_key: ${{secrets.ASOC_KEY}}
            asoc_secret: ${{secrets.ASOC_SECRET}}
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
